services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - MYSQL_SSL=true
    restart: unless-stopped
